---
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      sh -c '
        set -euo pipefail
        # Use $$ to prevent interpolation 
        if [ $$(id -u) -ne 1000 ]; then
          exit 1
        fi
        aspell --version # aspell
        base64 --version # coreutils
        curl --version # curl
        git --version # git
        echo | go-md2man # go-md2man
        markdown --version # markdown
        mdformat --version # mdformat
        pandoc --version # pandoc
        pip --version # py3-pip
        python --version # python3
      '
